
version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache
    # image: php:8.0-apache
    build:
      context: ./backend/
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./frontend/dist:/var/www/html
      - ./backend/:/var/www/html/php
    ports:
      - 8000:80
    # environment:
    #   - upload_max_filesize=10G
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
        MYSQL_DATABASE: MYSQL_DATABASE
        MYSQL_USER: MYSQL_USER
        MYSQL_PASSWORD: MYSQL_PASSWORD
    volumes:
        - ./initdb:/docker-entrypoint-initdb.d
        - mysql-data:/var/lib/mysql
    ports:
        - "9906:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - '8080:80'
    restart: always
    environment:
        PMA_HOST: db
    depends_on:
        - db
  
volumes:
  mysql-data:

 