version: '3'
services:
  frontend:
    build:
      context: ./docker/client
    ports:
      - "8080:8080"
    volumes:
      - ./client:/app

  backend:
    build:
      context: ./docker/server
    ports:
      - "80:80"
    volumes:
      - ./server:/var/www/html
    depends_on:
      - client

  # db:
  #   image: mysql:latest
  #   environment:
  #     - MYSQL_DATABASE=php_vuejs_file_manager
  #     - MYSQL_USER=php_project
  #     - MYSQL_PASSWORD=password # this should live in a env var
  #     - MYSQL_ALLOW_EMPTY_PASSWORD=1 # equivalent to True
  #   volumes:
  #     - "./db:/docker-entrypoint-initdb.d" #sync persistent sql files with container
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   ports:
  #     - 8001:80
  #   environment:
  #     - PMA_HOST=db
  #     - PMA_PORT=3306